In [42]:
import numpy as np 
import pandas as pd
import scipy as sc
from codetriangle.sentropies import *
from codetriangle.jentropies import *

In [43]:
import pandas as pd
import numpy as np
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data', names = ['Sample code number','Clump Thickness','Uniformity of Cell Size','Uniformity of Cell Shape','Marginal Adhesion','Single Epithelial Cell Size','Bare Nuclei','Bland Chromatin','Normal Nucleoli','Mitoses','Class'])
df = df.drop(['Sample code number'],axis = 1)

from sklearn.preprocessing import LabelEncoder   #' Used for discretization

In [44]:
edf = sentropies_df(df)

233


/Users/jaime.de.los.rios/Documents/Jupyter Prueba Fran/codetriangle/sentropies.py:92: UserWarning: Discretizing data from X DataFrame before entropy calculation!
  warnings.warn("Discretizing data from X DataFrame before entropy calculation!") #' Throwing a Warning for communicating a discretization of data
/Users/jaime.de.los.rios/Documents/Jupyter Prueba Fran/codetriangle/auxfunc.py:33: UserWarning: Discretizing data!
  warnings.warn("Discretizing data!")


In [22]:
def smetcoords(df,scale=100):

    c = list()
    for i in range(df.shape[0]):
        if(df.iloc[i].values[2:6].sum()>1):
            c.append((df.iloc[i].values[2:6])/df.iloc[i].values[0])
        #else:
            #c.append(df.iloc[i].values[2:6])
    c = list(map(lambda x: x * scale, c))
    
    return c


In [20]:
points = smetcoords(edf)

[array([ 8.37341609, 64.1810458 , 27.44553811]),
 array([29.68312158, 67.73670894,  2.58016947]),
 array([24.91818804, 67.58672108,  7.49509089]),
 array([33.9029452 , 61.39805651,  4.69899829]),
 array([31.16966848, 61.57314322,  7.2571883 ]),
 array([39.17339488, 55.98712652,  4.83947861]),
 array([16.7303389 , 64.88047532, 18.38918578]),
 array([38.39666156, 58.66137849,  2.94195995]),
 array([64.97290247, 33.71487686,  1.31222067]),
 array([30.98927071, 60.71742157,  8.29330772])]

In [23]:
df1 = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', names = ['sepal length','sepal width','petal length','petal width','class'])

In [30]:
edf1 = sentropies_df(df1,type = 'dual')

50


/Users/jaime.de.los.rios/Documents/Jupyter Prueba Fran/codetriangle/sentropies.py:92: UserWarning: Discretizing data from X DataFrame before entropy calculation!
  warnings.warn("Discretizing data from X DataFrame before entropy calculation!") #' Throwing a Warning for communicating a discretization of data
/Users/jaime.de.los.rios/Documents/Jupyter Prueba Fran/codetriangle/auxfunc.py:33: UserWarning: Discretizing data!
  warnings.warn("Discretizing data!")


In [31]:
points1 = smetcoords(edf1)

In [32]:
points1

[array([65.63882058, 33.12537459,  1.23580484])]

In [33]:
edf1

H_Ux      H_Px  DeltaH_Px     D_Px     VI_Px
Name                                                   
All   20.906692  7.183786  13.722906  6.92542  0.258366

In [35]:
from random import choice
def markers(n) :
    
    filled_markers = ('o', 'v', '^', '<', '>', '8', 's', 'p', '*', 'h', 'H', 'D', 'd', 'P', 'X')
    
    mk = list()
    for i in range(n) : mk.append(choice(filled_markers))
    
    return mk

In [40]:
a = markers(10)